### ISSUE TITLE
Trouble with installation

### ISSUE THREAD

**Issue by jswlinux** [SexualHealthInnovations/callisto-sample-project#46]
Dear developers,

Today I've tried to install callisto-sample-project in my developing environment, but there is something that I can't solve.

**Steps to reproduce**
`$ git clone https://github.com/SexualHealthInnovations/callisto-sample-project`
`$ cd callisto-sample-project`
`$ mkvirtualenv --python=python3 callisto-sample-project`
`$ source bin/activate`
`$ npm install`
=> It didn't work properly for permission issues.  So I ran this command as root, and everything seemed looking good.
`$ pip install -r requirements/local.txt`
`$ createdb callisto-sample-project`
`$ ./manage.py migrate`
`$ python manage.py createsuperuser`
`$ npm start`

**Expected behaviour**
It should show a main page

**Server configuration**
Ubuntu 14.04 64bit
Python 3.4
Django 1.9.8
PostgreSQL 9.3

**Logs**
`$npm start`
> (callisto-sample-project) ubuntu@callisto:~/callisto-sample-project$ npm start
> callisto-sample-project@0.1.0 start /home/ubuntu/callisto-sample-project
> npm run dev & npm run python

> callisto-sample-project@0.1.0 python /home/ubuntu/callisto-sample-project
> python manage.py runserver

> callisto-sample-project@0.1.0 dev /home/ubuntu/callisto-sample-project
> NODE_ENV=local npm run babel -- ./node_modules/.bin/webpack-dev-server --progress --hot --host=0.0.0.0

> Performing system checks...

> System check identified no issues (0 silenced).
> September 14, 2016 - 01:40:05
> Django version 1.9.9, using settings 'config.settings.local'
> Starting development server at http://127.0.0.1:8000/
> Quit the server with CONTROL-C.

*Error Log*
OSError: Error reading /home/ubuntu/callisto-sample-project/webpack-stats.json. Are you sure webpack has generated the file and the path is correct?

==
The file, `/home/ubuntu/callisto-sample-project/webpack-stats.json` does not exist.  I tried to figure out how to generate this json file; I found a command from googling:

`$ node_modules/webpack/bin/webpack.js --json > stats.json`

When I ran this command, the error message was:
> /home/ubuntu/callisto-sample-project/webpack.config.js:19
> module.exports = (() => {
>                    ^
(19 white spaces)

> SyntaxError: Unexpected token )
>     at Module._compile (module.js:439:25)
>     at Object.Module._extensions..js (module.js:474:10)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:312:12)
>     at Module.require (module.js:364:17)
>     at require (module.js:380:17)
>     at module.exports (/home/ubuntu/callisto-sample-project/node_modules/webpack/bin/convert-argv.js:93:13)
>     at Object.<anonymous> (/home/ubuntu/callisto-sample-project/node_modules/webpack/bin/webpack.js:135:40)
>     at Module._compile (module.js:456:26)
>   at Object.Module._extensions..js (module.js:474:10)

I tried to generate an empty file, then the Django page said
> Error during template rendering
> In template /home/ubuntu/callisto-sample-project/callisto_sample_project/templates/pages/home.html, error at line 0
> Expecting value: line 1 column 1 (char 0)
> 1	{% extends "base.html" %}

Thank you in advance!

**Comment by kevindaum** [comment]
Before I dig into this, have you tried waiting a couple minutes after running `npm start`? When I was running the project with docker containers, I watched the output coming from the django/npm/mailhog container and waited until I saw `npm_1 | webpack: bundle is now VALID.`. I wrote this in the README, which sounds like what you're experiencing:

> You may have to wait quite some time before webpack finishes building the bundle of static files. If you try to access the site before it's finished, you'll probably see a traceback for `builtins.OSError: Error reading /app/webpack-stats.json. Are you sure webpack has generated the file and the path is correct?`. Once you see `npm_1 | webpack: bundle is now VALID.`, your django/npm/mailhog server is running.

**Comment by jswlinux** [comment]
Yes, I've tried to wait 5 minutes after running npm start.  The tarceback message looks similar, but the root cause seems like, it doesn't generate a `webpack-stats.json` file.  Currently I'm running the project in a virtual instance on OpenStack IceHouse, so I'm not sure how I can see the npm log; there was no log file generated in $HOME.

Also, like I wrote the above, I tried to generate an empty `webpack-stats.json` file, the error message from Django was different.  It said `Expecting value: line 1 column 1 (char 0)`.  The line #1 in `home.html` file is {% extends "base.html" %}.  I'm guessing that `webpack-stats.json` file should contain some critical information to load template files properly, because `config/webpack.local.config.js` is supposed to create a `webpack-stats.json` file to track something (Sorry, I'm a sysadmin, not a programmer; I'm not able to fully understand the code).

Please guide me if I'm missing anything.  One of our educational development coordinator wants to review this project to gain insight for our own development for a few weeks.

Thanks

**Comment by jswlinux** [comment]
FYI, here is the traceback:

==
System check identified no issues (0 silenced).
September 14, 2016 - 19:51:47
Django version 1.9.8, using settings 'config.settings.local'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 174, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 172, in get_response
    response = response.render()
  File "/usr/local/lib/python3.4/dist-packages/django/template/response.py", line 160, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.4/dist-packages/django/template/response.py", line 137, in rendered_content
    content = template.render(context, self._request)
  File "/usr/local/lib/python3.4/dist-packages/django/template/backends/django.py", line 95, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.4/dist-packages/django/template/base.py", line 206, in render
    return self._render(context)
  File "/usr/local/lib/python3.4/dist-packages/django/test/utils.py", line 92, in instrumented_test_render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.4/dist-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.4/dist-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.4/dist-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.4/dist-packages/django/test/utils.py", line 92, in instrumented_test_render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.4/dist-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.4/dist-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.4/dist-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python3.4/dist-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.4/dist-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.4/dist-packages/django/template/library.py", line 201, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/webpack_loader/templatetags/webpack_loader.py", line 40, in render_bundle
    return render_as_tags(_get_bundle(bundle_name, extension, config))
  File "/usr/local/lib/python3.4/dist-packages/webpack_loader/templatetags/webpack_loader.py", line 32, in _get_bundle
    bundle = get_loader(config).get_bundle(bundle_name)
  File "/usr/local/lib/python3.4/dist-packages/webpack_loader/loader.py", line 54, in get_bundle
    assets = self.get_assets()
  File "/usr/local/lib/python3.4/dist-packages/webpack_loader/loader.py", line 33, in get_assets
    return self._load_assets()
  File "/usr/local/lib/python3.4/dist-packages/webpack_loader/loader.py", line 21, in _load_assets
    return json.load(f)
  File "/usr/lib/python3.4/json/__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
[14/Sep/2016 20:00:36] "GET / HTTP/1.1" 500 214987
[14/Sep/2016 20:00:37] "GET /static/debug_toolbar/js/jquery_pre.js HTTP/1.1" 304 0
[14/Sep/2016 20:00:37] "GET /static/debug_toolbar/css/toolbar.css HTTP/1.1" 304 0
[14/Sep/2016 20:00:37] "GET /static/debug_toolbar/js/jquery_post.js HTTP/1.1" 304 0
[14/Sep/2016 20:00:37] "GET /static/debug_toolbar/js/toolbar.js HTTP/1.1" 304 0
[14/Sep/2016 20:00:37] "GET /static/debug_toolbar/img/ajax-loader.gif HTTP/1.1" 304 0
[14/Sep/2016 20:00:37] "GET /static/debug_toolbar/css/print.css HTTP/1.1" 304 0

**Comment by kelseyq** [comment]
@jswlinux I've responded to your coordinator in gitter, but this is a very much in-progress sample project using the [callisto-core](https://github.com/sexualhealthinnovations/callisto-core) library. You and your coworkers are welcome to get in touch with me to learn more about the Callisto project and the open source aspects of our work at kelsey@sexualhealthinnovations.org. Thanks!

**Comment by figureone** [comment]
I reviewed the npm logs from @jswlinux and it looks like webpack wasn't installed due to a permissions error:
```
94 error git fetch -a origin (git://github.com/goldhand/karma-webpack) error: cannot open FETCH_HEAD: Permission denied
...
104 error Error: No compatible version found: karma-webpack@'goldhand/karma-webpack'
```

I'll try to get that one solved, it should address the original issue reported here.
